### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by yceffort-naver** [NaverPayDev/hidash#39]
## TODO

thanks to @byhhh2 

- [ ] [includes](https://unpkg.com/lodash/includes.js)
- [ ] [eq](https://unpkg.com/lodash/eq.js)
- [ ] [every](https://unpkg.com/lodash/every.js)
- [ ] [flow](https://unpkg.com/lodash/flow.js)
- [ ] [isEmpty](https://unpkg.com/lodash/isEmpty.js)
- [ ] [isNull](https://unpkg.com/lodash/isNull.js)
- [ ] [clone](https://unpkg.com/lodash/clone.js)
- [ ] [isString](https://unpkg.com/lodash/isString.js)
- [ ] [cloneDeep](https://unpkg.com/lodash/cloneDeep.js)
- [ ] [isObject](https://unpkg.com/lodash/isObject.js)
- [ ] [map](https://unpkg.com/lodash/map.js)
- [ ] [values](https://unpkg.com/lodash/values.js)
- [ ] [isNil](https://unpkg.com/lodash/isNil.js)
- [ ] [merge](https://unpkg.com/lodash/merge.js)
- [ ] [isError](https://unpkg.com/lodash/isError.js)
- [ ] [pick](https://unpkg.com/lodash/pick.js)
- [ ] [isEqual](https://unpkg.com/lodash/isEqual.js)
- [ ] [groupBy](https://unpkg.com/lodash/groupBy.js)
- [ ] [isNumber](https://unpkg.com/lodash/isNumber.js)
- [ ] [isFunction](https://unpkg.com/lodash/isFunction.js)
- [ ] [toString](https://unpkg.com/lodash/toString.js)
- [ ] [isUndefined](https://unpkg.com/lodash/isUndefined.js)
- [ ] [findLastIndex](https://unpkg.com/lodash/findLastIndex.js)
- [ ] [find](https://unpkg.com/lodash/find.js)
- [ ] [flatten](https://unpkg.com/lodash/flatten.js)
- [ ] [gt](https://unpkg.com/lodash/gt.js)
- [ ] [head](https://unpkg.com/lodash/head.js)
- [ ] [omit](https://unpkg.com/lodash/omit.js)
- [ ] [get](https://unpkg.com/lodash/get.js)
- [ ] [uniq](https://unpkg.com/lodash/uniq.js)
- [ ] [uniqBy](https://unpkg.com/lodash/uniqBy.js)
- [ ] [parseIntFp](https://unpkg.com/lodash/parseInt.js)
- [ ] [trim](https://unpkg.com/lodash/trim.js)
- [ ] [first](https://unpkg.com/lodash/first.js)
- [ ] [pipe](https://unpkg.com/lodash/flow.js)
- [ ] [contains](https://unpkg.com/lodash/includes.js)
- [ ] [equals](https://unpkg.com/lodash/eq.js)
- [ ] [toNumber](https://unpkg.com/lodash/toNumber.js)
- [ ] [assign](https://unpkg.com/lodash/assign.js)
- [ ] [isArray](https://unpkg.com/lodash/isArray.js)
- [ ] [some](https://unpkg.com/lodash/some.js)
- [ ] [mapValues](https://unpkg.com/lodash/mapValues.js)
- [ ] [filter](https://unpkg.com/lodash/filter.js)
- [ ] [toPairs](https://unpkg.com/lodash/toPairs.js)
- [ ] [last](https://unpkg.com/lodash/last.js)
- [ ] [union](https://unpkg.com/lodash/union.js)
- [ ] [findIndex](https://unpkg.com/lodash/findIndex.js)
- [ ] [sortBy](https://unpkg.com/lodash/sortBy.js)
- [ ] [uniqWith](https://unpkg.com/lodash/uniqWith.js)
- [ ] [difference](https://unpkg.com/lodash/difference.js)
- [ ] [entries](https://unpkg.com/lodash/toPairs.js)
- [ ] [join](https://unpkg.com/lodash/join.js)
- [ ] [prop](https://unpkg.com/lodash/get.js)
- [ ] [has](https://unpkg.com/lodash/has.js)
- [ ] [mergeWith](https://unpkg.com/lodash/mergeWith.js)
- [ ] [sum](https://unpkg.com/lodash/sum.js)
- [ ] [sumBy](https://unpkg.com/lodash/sumBy.js)
- [ ] [chunk](https://unpkg.com/lodash/chunk.js)
- [ ] [times](https://unpkg.com/lodash/times.js)
- [ ] [padCharsStart](https://unpkg.com/lodash/padStart.js)
- [ ] [isPlainObject](https://unpkg.com/lodash/isPlainObject.js)
- [ ] [lt](https://unpkg.com/lodash/lt.js)
- [ ] [repeat](https://unpkg.com/lodash/repeat.js)

**Comment by yceffort-naver** [comment]
duplicated #122
